# Generated by Django 5.0.6 on 2024-07-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_img', models.ImageField(upload_to='doctors/')),
                ('spec', models.CharField(max_length=50)),
            ],
        ),
    ]
