# Generated by Django 5.0.6 on 2024-07-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userdata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=100)),
            ],
        ),
    ]
