# Generated by Django 5.0.6 on 2024-07-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alogin',
            old_name='username',
            new_name='email',
        ),
    ]
